{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-config-maps.fullname" . }}-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["indeed.com"]
    resources: ["clusterconfigmaps"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-config-maps.fullname" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-config-maps.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "cluster-config-maps.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}