// Code generated by mockery v2.9.4. DO NOT EDIT.

package ccm

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockVolumePublisher is an autogenerated mock type for the VolumePublisher type
type mockVolumePublisher struct {
	mock.Mock
}

// Mount provides a mock function with given fields: ctx, meta
func (_m *mockVolumePublisher) Mount(ctx context.Context, meta *ClusterConfigMapMeta) error {
	ret := _m.Called(ctx, meta)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ClusterConfigMapMeta) error); ok {
		r0 = rf(ctx, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Populate provides a mock function with given fields: ctx, meta
func (_m *mockVolumePublisher) Populate(ctx context.Context, meta *ClusterConfigMapMeta) error {
	ret := _m.Called(ctx, meta)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ClusterConfigMapMeta) error); ok {
		r0 = rf(ctx, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
